# Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

## `numpy.array()` vs `array.array()`

- `array.array()` is from Python's standard library. It creates a lightweight **1D typed container** for basic values like integers and floats.
- `numpy.array()` creates a `numpy.ndarray`, which supports **1D, 2D, and higher-dimensional arrays**.
- `array.array()` is mainly for compact storage. `numpy.array()` is for **numerical computing**, vectorized math, reshaping, slicing, and broadcasting.
- `array.array()` uses type codes like `'i'` or `'f'`. NumPy supports many `dtype` options such as `int32`, `float64`, and `bool`.
- `+` behaves differently: `array.array('i', [1, 2]) + array.array('i', [3, 4])` concatenates, while `np.array([1, 2]) + np.array([3, 4])` gives element-wise addition: `[4 6]`.

Use `array.array()` when you only need a simple typed 1D sequence. Use `numpy.array()` when you need fast array operations and data analysis workflows.

In [1]:
import numpy as np

# create a 1D array
arr = np.array([1, 2, 3, 4, 5]) # converts the list to a numpy array
print(arr) # prints the array
print(type(arr)) # prints the type of the array
print(arr.shape) # prints the shape of the array
print(arr.dtype) # prints the data type of the array elements

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int64


In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # creates a 2D array
print(arr2) # prints the 2D array
print(arr2.shape) # prints the shape of the 2D array, 2 rows and 3 columns
print(arr2.dtype) # prints the data type of the 2D array elements
arr2.reshape(3, 2) # reshapes the array to 3 rows and 2 columns
arr2.reshape(1,6) # reshapes the array to 6 elements

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


array([[1, 2, 3, 4, 5, 6]])

In [17]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]]) # creates a 2D array as there are 2 lists inside the main list [[1, 2, 3], [4, 5, 6]]
print(f"Array:\n{arr3}") # prints the 2D array
print(f"Shape: {arr3.shape}") # prints the shape of the 2D array, 2 rows and 3 columns
print(f"Data type: {arr3.dtype}") # prints the data type of the 2D array elements
print(f"Transpose:\n{arr3.T}") # prints the transpose of the array, which is a new array with rows and columns swapped
print(f"Item size: {arr3.itemsize} bytes") # prints the size of each element in bytes
arr3.reshape(3, 2) # reshapes the array to 3 rows and 2 columns
arr3.reshape(1,6) # reshapes the array to 6 elements

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data type: int64
Transpose:
[[1 4]
 [2 5]
 [3 6]]
Item size: 8 bytes


array([[1, 2, 3, 4, 5, 6]])

In [10]:
print(np.arange(0, 10, 2)) # creates an array of numbers from 0 to 10 with a step of 2
print(np.arange(0, 10, 2).reshape(5, 1)) # creates an array of numbers from 0 to 10 with a step of 2 and reshapes it to 5 rows and 1 column

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [14]:
print(np.ones((2, 3))) # creates a 2D array of ones with 2 rows and 3 columns
print(np.zeros((3, 4))) # creates a 2D array of zeros with 3 rows and 4 columns

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
# identity matrix
print(np.eye(4)) # creates a 4x4 identity matrix, which is a square matrix with ones on the main diagonal and zeros elsewhere

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
# Numpy Vectorized Operations
arr4 = np.array([1, 2, 3, 4, 5]) # creates a 1D array
arr5 = np.array([10, 20, 30, 40, 50]) # creates another 1D array

# element-wise addition
print(f"Element-wise addition:\n{arr4 + arr5}") # adds the two arrays element-wise

# element wise subtraction
print(f"Element-wise subtraction:\n{arr4 - arr5}") # subtracts the two arrays element-wise

# element-wise multiplication
print(f"Element-wise multiplication:\n{arr4 * arr5}") # multiplies the two arrays element-wise

# element-wise division
print(f"Element-wise division:\n{arr4 / arr5}") # divides the two arrays element-wise

Element-wise addition:
[11 22 33 44 55]
Element-wise subtraction:
[ -9 -18 -27 -36 -45]
Element-wise multiplication:
[ 10  40  90 160 250]
Element-wise division:
[0.1 0.1 0.1 0.1 0.1]


In [19]:
# universal functions

arr6 = np.array([2,3,4,5,6]) # creates a 1D array

print(f"Square root:\n{np.sqrt(arr6)}") # applies the square root function to each element of the array
print(f"Exponential:\n{np.exp(arr6)}") # applies the exponential function to each element of the array
print(f"Logarithm:\n{np.log(arr6)}") # applies the logarithm function to each element of the array
print(f"Sin:\n{np.sin(arr6)}") # applies the sine function to each element of the array
print(f"Cosine:\n{np.cos(arr6)}") # applies the cosine function to each element of the array
print(f"Tangent:\n{np.tan(arr6)}") # applies the tangent function to each element of the array

Square root:
[1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Logarithm:
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Sin:
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Cosine:
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
Tangent:
[-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]


In [ ]:
# array slicing and indexing
arr7 = np.array([[1, 2, 3,4], [5, 6, 7, 8], [9, 10, 11, 12]]) # creates a 2D array
print(f"Array:\n{arr7}") # prints the 2D array


print(f"First element:\n{arr7[0][0]}") # prints the first element of the array

print(f"First row:\n{arr7[0]}") # prints the first row of the array
print(f"Second column:\n{arr7[:, 1]}") # prints the second column of the array
print(f"Subarray (first two rows and first three columns):\n{arr7[:2, :3]}") 
# prints a subarray consisting of the first two rows and the first three columns

# first [] - represents the row index, second [] - represents the column index, 
# we can add slice and steps in the indices to select specific elements, rows, columns, or subarrays
# [start:stop:step] for rows and columns

print(f"Every other row:\n{arr7[::2]}") # prints every other row of the array
print(f"Every other column:\n{arr7[:, ::2]}") # prints every other column of the array
print(f"Get some elements:\n{arr7[1::1, 0::2]}") # prints a subarray consisting of every row starting from the second row and every other column starting from the first column

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First element:
1
First row:
[1 2 3 4]
Second column:
[ 2  6 10]
Subarray (first two rows and first three columns):
[[1 2 3]
 [5 6 7]]
Every other row:
[[ 1  2  3  4]
 [ 9 10 11 12]]
Every other column:
[[ 1  3]
 [ 5  7]
 [ 9 11]]
Get some elements:
[[5 6 7 8]]


In [ ]:
# Statistics - Normalization and Standardization
arr8 = np.array([1, 2, 3, 4, 5]) # creates a 1D array
print(f"Original array:\n{arr8}") # prints the original array
print(f"Mean: {np.mean(arr8)}") # calculates and prints the mean of the array
print(f"Standard deviation: {np.std(arr8)}") # calculates and prints the standard deviation of the array
print(f"Normalized array:\n{(arr8 - np.mean(arr8)) / np.std(arr8)}") # normalizes the array by subtracting the mean and dividing by the standard deviation

Original array:
[1 2 3 4 5]
Mean: 3.0
Standard deviation: 1.4142135623730951
Normalized array:
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [32]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
print((data>=5) & (data<=8)) # returns a boolean array where the condition is true for elements between 5 and 8 (inclusive)
data[(data>=5) & (data<=8)] # and - will not work without parentheses as the precedence of & is lower than comparison operators, 
# so we need to use parentheses to group the conditions together

[False False False False  True  True  True  True False False]


array([5, 6, 7, 8])